### ISSUE TITLE
Won't build for 32bit systems, e.g. ESP32

### ISSUE THREAD

**Issue by brianmay** [akiles/atomic-polyfill#14]
This crate is required because `shared-bus` 0.2.3 now depends on it.

```
at 09:24:22 ❯ cargo build                                                                                      
   Compiling atomic-polyfill v0.1.6
   Compiling robotica-remote-rust v0.22.8 (/home/brian/tree/personal/robotica-remote-rust)
error[E0432]: unresolved import `core::sync::atomic::AtomicU64`
   --> /home/brian/.cargo/registry/src/github.com-1ecc6299db9ec823/atomic-polyfill-0.1.6/src/lib.rs:8:17
    |
8   |         pub use core::sync::atomic::$atomic_type;
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `AtomicU64` in `sync::atomic`
...
195 | atomic_int!(u64, AtomicU64, u64_native, u64_cas, u64_full);
    | ----------------------------------------------------------
    | |                |
    | |                help: a similar name exists in the module: `AtomicU8`
    | in this macro invocation
    |
    = note: this error originates in the macro `atomic_int` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0432]: unresolved import `core::sync::atomic::AtomicI64`
   --> /home/brian/.cargo/registry/src/github.com-1ecc6299db9ec823/atomic-polyfill-0.1.6/src/lib.rs:8:17
    |
8   |         pub use core::sync::atomic::$atomic_type;
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `AtomicI64` in `sync::atomic`
...
200 | atomic_int!(i64, AtomicI64, i64_native, i64_cas, i64_full);
    | ----------------------------------------------------------
    | |                |
    | |                help: a similar name exists in the module: `AtomicI8`
    | in this macro invocation
    |
    = note: this error originates in the macro `atomic_int` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0432`.
error: could not compile `atomic-polyfill` due to 2 previous errors
```

**Comment by Dirbaio** [comment]
Which `--target` are you building for?

**Comment by brianmay** [comment]
xtensa-esp32-espidf

**Comment by brianmay** [comment]
Looking at the rust code from `atomic.rs` I suspect it needs to be made conditional on:

```
#[cfg(target_has_atomic_load_store = "64")]
```

https://doc.rust-lang.org/src/core/sync/atomic.rs.html#2204

**Comment by Dirbaio** [comment]
The reason we're not using that is it's nightly-only. Instead the individual targets are added to build.rs here: https://github.com/embassy-rs/atomic-polyfill/blob/main/build.rs#L31-L43

I can add xtensa real quick. Could you confirm whether the xtensa targets have atomics up to 32bits, and whether they support CAS operations?

**Comment by MabezDev** [comment]
As of rustc 1.59 (our fork on esp-rs) all our espidf targets support up to 64 bit atomics (note that you'll need to use at least esp-idf v4.4 to get the required patches). As for baremetal targets, it depends on the chip.

| Target                  | Max atomic width | CAS |
|-------------------------|------------------|-----|
| xtensa-esp32-espidf     | 64               | yes |
| xtensa-esp32-none-elf   | 32               | yes |
| xtensa-esp32s2-espidf   | 64               | yes |
| xtensa-esp32s2-none-elf | 0<sup>1</sup>                | no  |
| xtensa-esp32s3-espidf   | 64               | yes |
| xtensa-esp32s3-none-elf | 32               | yes |
| xtensa-esp8266-none-elf | 32               | no  |

<sup>1</sup> In theory the arch specification for xtensa guarantees that all word access is atomic, but like the RISCV llvm backend this isn't implemented (yet?).

**Comment by brianmay** [comment]
Am using esp-idf v4.4.

Not sure I understand 100% if this means it should work as is or if changes are required.

**Comment by Dirbaio** [comment]
@MabezDev isn't esp32s2 xtensa also?

**Comment by MabezDev** [comment]
> @MabezDev isn't esp32s2 xtensa also?

Yes, all the targets listed above are xtensa.

> Not sure I understand 100% if this means it should work as is or if changes are required.

This crate won't work just yet. We'll need to update the build script that decides if atomics need polyfilling for the xtensa targets.

* We can ignore all `*-espidf-*` targets and just reexport core
* For baremetal it might get a bit trickier:
  *  There is the `s32c1i` CPU feature which we can use to detect CAS on an xtensa target
  * I'm not sure if we can figure out the atomic width of a target so easily

**Comment by Dirbaio** [comment]
Added xtensa support. Hopefully I did it right, I have no hardware to test! 

https://github.com/embassy-rs/atomic-polyfill/blob/528bb3930c73e7d272a739991998f447e03b7aa2/build.rs#L42-L46

**Comment by Dirbaio** [comment]
Fixed in 0.1.7

**Comment by brianmay** [comment]
Hmmm. Getting the same error. Did I do something wrong?

```
   Compiling atomic-polyfill v0.1.7
error[E0432]: unresolved import `core::sync::atomic::AtomicU64`
   --> /home/brian/.cargo/registry/src/github.com-1ecc6299db9ec823/atomic-polyfill-0.1.7/src/polyfill.rs:6:17
    |
6   |         pub use core::sync::atomic::$atomic_type;
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `AtomicU64` in `sync::atomic`
...
193 | atomic_int!(u64, AtomicU64, u64_native, u64_cas, u64_full);
    | ----------------------------------------------------------
    | |                |
    | |                help: a similar name exists in the module: `AtomicU8`
    | in this macro invocation
    |
    = note: this error originates in the macro `atomic_int` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0432]: unresolved import `core::sync::atomic::AtomicI64`
   --> /home/brian/.cargo/registry/src/github.com-1ecc6299db9ec823/atomic-polyfill-0.1.7/src/polyfill.rs:6:17
    |
6   |         pub use core::sync::atomic::$atomic_type;
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `AtomicI64` in `sync::atomic`
...
198 | atomic_int!(i64, AtomicI64, i64_native, i64_cas, i64_full);
    | ----------------------------------------------------------
    | |                |
    | |                help: a similar name exists in the module: `AtomicI8`
    | in this macro invocation
    |
    = note: this error originates in the macro `atomic_int` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0432`.
error: could not compile `atomic-polyfill` due to 2 previous errors
```

**Comment by Dirbaio** [comment]
It builds fine for me. Maybe you need to update your xtensa rust?
```
[dirbaio@mars atomic-polyfill]$ rustc +esp --version
rustc 1.59.0-dev
[dirbaio@mars atomic-polyfill]$ cargo +esp build -Zbuild-std --target xtensa-esp32-espidf
...
    Finished dev [unoptimized + debuginfo] target(s) in 19.19s
```

**Comment by brianmay** [comment]
Oh, of course. I thought "rustup update" would update the compiler, but as the esp32 version was manually installed it won't update that. I was on 1.58.0-dev. Now fixed, and it compiles and works fine.
