### ISSUE TITLE
Minimum Safe Rust Version

### ISSUE THREAD

**Issue by notgull** [akiles/atomic-polyfill#19]
Does this crate have an MSRV policy? I doubt that it's any recent version of Rust (since it just re-exports `core` primitives or redefines them using relatively low-level types), but it would be nice to know for when users want to include it in their projects.

**Comment by Dirbaio** [comment]
currently 1.54+, same as `critical-section`: https://github.com/rust-embedded/critical-section#minimum-supported-rust-version-msrv. Only guarantee is "latest stable Rust", so this might be bumped in minor/patch releases.

PRs welcome to update the README :)

**Comment by Dirbaio** [comment]
Fixed in 17a308be208be250858d9f93708590a64f85a177
