### ISSUE TITLE
Implement Arc and Weak using items from this crate

### ISSUE THREAD

**Issue by notgull** [akiles/atomic-polyfill#22]
I'd like to use this in a crate that also uses `Arc`. Theoretically, it should be possible to also re-export/re-implement the `Arc` and `Weak` types using this crate. Maybe lock it behind an `alloc` feature for targets without an allocator available.

I can implement this PR myself.

**Comment by Dirbaio** [comment]
I would like for this crate to stick to just being a `core::sync::atomic` polyfill. You're welcome to implement this in your own crate, we can add a link to it in the README here :)
