### ISSUE TITLE
Should deprecated stuff be available? 

### ISSUE THREAD

**Issue by Dirbaio** [akiles/atomic-polyfill#3]
Currently this crate doesn't make available deprecated items in polyfilled mode. This includes:

- The `compare_and_swap` method on all atomic types
- The `ATOMIC_XX_INIT` consts
- The `spin_loop_hint` function

To me this doesn't seem a big deal because if you're migrating some code from `core::sync::atomic` to `atomic_polyfill` you're already doing modifications, 

OTOH it might be annoying to have code that compiles in non-polyfilled mode and fails in polyfilled mode. If we aim to be a complete drop-in replacement maybe deprecated items should be available too...

Thoughts?

**Comment by Lokathor** [comment]
Could put it behind an `allow_deprecated` cargo feature that's off by default, if you really wanna encourage people to move away from the old stuff by default.

**Comment by Dirbaio** [comment]
These have been missing for a while and no one has complained, so I guess the answer is "no, they're not available" :)
