### ISSUE TITLE
Revisit Build-Script Polyfill Level Granularity

### ISSUE THREAD

**Issue by torrancew** [akiles/atomic-polyfill#9]
The compile-time features in the crate are fairly granular, but in `build.rs` they are more coarse.
In practice, this means that platforms such as AVR can't express that they natively support some
atomic operations on small-width integer types, but need polyfills on larger ones to the build process.

Would you be open to a patch that makes the built-in tuning in `build.rs` a bit more granular?

**Comment by Dirbaio** [comment]
What granularity are you missing exactly? The build script already has features for each integer size. Is it different operations (like it can do atomic add but not atomic sub)?

Either way, the goal is to support as many targets as possible, so if it's needed the answer is yes, I guess :)

**Comment by Dirbaio** [comment]
Closing due to lack of response. If you have a particular example of some hardware that can do X but not Y in hardware, and the current features are too coarse to separate X and Y please open a new issue.
